version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stats" ]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmdb
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  stats-server:
    build: ./stats-service/server
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db/stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ./ewm-service
    container_name: ewm
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db/ewm
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
